export const footerLinks = [
  {
    title: "Products",
    links: [
      { title: "IP Camera", url: "/" },
      { title: "Network Video Recorders", url: "/" },
      { title: "Speed Dome", url: "/" },
      { title: "Accessories", url: "/" },
      { title: "Software", url: "/" },
      { title: "Switch", url: "/" },
    ],
  },
  {
    title: "Solutions",
    links: [
      { title: "Color Maker", url: "/" },
      { title: "Early Warning", url: "/" },
      { title: "Face Recognition", url: "/" },
      { title: "Panaromic", url: "/" },
      { title: "Starlight Technology", url: "/" },
    ],
  },
  {
    title: "Support",
    links: [
      { title: "Technical Support", url: "/" },
      { title: "About Us ", url: "/" },
      { title: "Download", url: "/" },
      { title: "Contact Us ", url: "/" },
      { title: "Customer Portal ", url: "/" },
      { title: "How To ", url: "/" },
      { title: "Product Selector ", url: "/" },
      { title: "Sales Contact ", url: "/" },
    ],
  },
  {
    title: "Features",
    links: [
      { title: "Inventory Tracking", url: "/" },
      { title: "Online Payments", url: "/" },
    ],
  },
];

export const manufacturers = [
  "Hikvision",
  "Axis Communications",
  "Dahuba Technology",
  "Dahua",
  "Bosch",
  "Samsung",
  "Sony",
  "Hanwha Vision",
  "Panasonic",
  "Honeywell",
  "Zicom",
  "Swann",
  "Av Tech",
  "Teledyne Flir",
  "Vanderbilt Industries",
  "Pelco",
  "Lorex",
  "IndigoVision",
  "Genetec",
  "IDIS",
  "Mobotix",
  "Vintron Informatics LTD",
  "Milestone Systems",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];
export const categoryItems = [
  {
    title: "IP Cameras",
    link: "/",
    image: "/cccamera1.png",
    subCategories: [
      { name: "2 MP", link: "/categories/item" },
      { name: "3 MP", link: "/categories/item" },
      { name: "4 MP", link: "/categories/item" },
      { name: "5 MP", link: "/categories/item" },
      { name: "8 MP (4K) ", link: "/categories/item" },
      { name: "Super Starlight", link: "/categories/item" },
      { name: "Color Maker", link: "/categories/item" },
      { name: "Vertical Lens", link: "/categories/item" },
      { name: "Fixed Lens", link: "/categories/item" },
      { name: "High AI", link: "/categories/item" },
    ],
  },
  {
    title: "PTZ",
    link: "/product/PTZ",
    image: "/cccamera2.png",
    subCategories: [
      { name: "2 MP PTZ", link: "/categories/item" },
      { name: "5 MP PTZ", link: "/categories/item" },
      { name: "8 MP PTZ", link: "/categories/item" },
      { name: "16 MP PTZ", link: "/categories/item" },
      { name: "High AI PTZ", link: "/categories/item" },
    ],
  },
  {
    title: "LPR",
    link: "/categories/item",
    image: "/cccamera3.png",
    subCategories: [
      { name: "TBD", link: "/categories/item" },
      { name: "TBD", link: "/categories/item" },
      { name: "TBD", link: "/categories/item" },
    ],
  },
  {
    title: "Fisheye & Panoramic",
    link: "/categories/item",
    image: "/cccamera1.png",
    subCategories: [
      { name: "TBD", link: "/categories/item" },
      { name: "TBD", link: "/categories/item" },
      { name: "TBD", link: "/categories/item" },
      { name: "TBD", link: "/categories/item" },
    ],
  },
  {
    title: "NVR",
    link: "/categories/item",
    image: "/cccamera2.png",
    subCategories: [
      { name: "Residential NVR ", link: "/categories/item" },
      { name: "Mid-Commercial NVR ", link: "/categories/item" },
      { name: "Commercial to Enterprise NVR ", link: "/categories/item" },
    ],
  },
  {
    title: "Based on Shape Factor",
    link: "/categories/item",
    image: "/cccamera3.png",
    subCategories: [
      { name: "Turret", link: "/categories/item" },
      { name: "Bullet", link: "/categories/item" },
      { name: "Dome ", link: "/categories/item" },
      { name: "PTZ ", link: "/categories/item" },
    ],
  },
  {
    title: "Doorbell Camers",
    link: "/categories/item",
    image: "/cccamera1.png",
    subCategories: [
      { name: "TBD", link: "/categories/item" },
      { name: "TBD", link: "/categories/item" },
      { name: "TBD ", link: "/categories/item" },
      { name: "TBD ", link: "/categories/item" },
    ],
  },
  {
    title: "IOT",
    link: "/categories/item",
    image: "/cccamera2.png",
    subCategories: [
      { name: "TBD", link: "/categories/item" },
      { name: "TBD", link: "/categories/item" },
      { name: "TBD ", link: "/categories/item" },
      { name: "TBD ", link: "/categories/item" },
      { name: "TBD ", link: "/categories/item" },
      { name: "TBD ", link: "/categories/item" },
    ],
  },
];
