export const products = [
  {
    image: "/camera.png",
    Series: "Spark",
    model: "TC-C32XN",
    Features: [
      "Up to 1920X1080@30fps",
      "·S+265/H.265/H.264",
      "·Min. illumination Color: 0.02Lux@F2.0",
      "·Smart IR, IR Range: 30m",
      "·Operating Conditions -30°~60°, 0~95% RH",
      "·POE",
    ],

    Zoom: "N/A",
    IRDistance: "N/A",
    Laser: "N/A",
    WDR: "N/A",
    Size: "N/A",
    MicroSDCardStorage: "N/A",
    Lens: "Fixed 2.8mm",
    BuiltInMic: true,
    AI: "Motion Detection",
    IO: "N/A",
    BuiltInSpeaker: false,
    Protection: "Indoor",
    OnBoardStorage: "N/A",
    Material: "Plastic Housing",
    Price: 30,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera1.png",
    Series: "Spark",
    model: "TC-C32QN",
    Features: [
      "·Up to 1920X1080@30fps",
      "·S+265/H.265/H.264",
      "·Min. illumination Color: 0.02Lux@F2.0",
      "·Smart IR, IR Range: 30m",
      "·Operating Conditions -30°~60°, 0~95% RH",
      "·POE",
    ],
    Zoom: "N/A",
    IRDistance: "N/A",
    Laser: "N/A",
    WDR: "N/A",
    Size: "N/A",
    MicroSDCardStorage: "N/A",
    Lens: "Fixed 2.8mm",
    BuiltInMic: true,
    AI: "Motion Detection",
    IO: "N/A",
    BuiltInSpeaker: false,
    Protection: "IP67",
    OnBoardStorage: "N/A",
    Material: "Metal+Plastic Housing",
    Price: 30,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera2.png",
    Series: "Lite Series Starlight",
    model: "TC-C34GN",
    Features: [
      "·Up to 1920X1080@30fps",
      "·S+265/H.265/H.264",
      "·Min. illumination Color: 0.02Lux@F2.0",
      "·Smart IR, IR Range: 30m",
      "·Operating Conditions -30°~60°, 0~95% RH",
      "·POE",
    ],
    Zoom: "N/A",
    IRDistance: "N/A",

    Laser: "N/A",
    WDR: "N/A",
    Size: "N/A",
    MicroSDCardStorage: "N/A",
    Lens: "Fixed 4mm",
    BuiltInMic: true,
    AI: "Tripwire / Perimeter",
    IO: "N/A",
    BuiltInSpeaker: false,
    Protection: "IP67",
    OnBoardStorage: "N/A",
    Material: "Metal+Plastic Housing",
    Price: 45,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera3.png",
    Series: "Lite Series WiFi",
    model: "TC-C32WN",
    Features: [
      "·Up to 1920X1080@30fps",
      "·S+265/H.265/H.264",
      "·Min. illumination Color: 0.02Lux@F2.0",
      "·Smart IR, IR Range: 30m",
      "·Operating Conditions -30°~60°, 0~95% RH",
      "·POE",
    ],

    Zoom: "N/A",
    IRDistance: "N/A",

    Laser: "N/A",
    WDR: "N/A",
    Size: "N/A",
    MicroSDCardStorage: "N/A",
    Lens: "Fixed 4mm",
    BuiltInMic: true,
    AI: "Motion Detection",
    IO: "N/A",
    BuiltInSpeaker: false,
    Protection: "IP67",
    OnBoardStorage: "Built-in MicroSD card slot, up to 512GB",
    Material: "Metal+Plastic Housing",
    Price: 65,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera4.png",
    Series: "Pro Series StarLight",
    model: "TC-H326S",
    Features: [
      "·Up to 1920X1080@30fps",
      "·S+265/H.265/H.264",
      "·Min. illumination Color: 0.02Lux@F2.0",
      "·Smart IR, IR Range: 30m",
      "·Operating Conditions -30°~60°, 0~95% RH",
      "·POE",
    ],
    Lens: "4.6mm~ 152mm",
    Zoom: "33X Optical Lens",
    IRDistance: "200m",
    BuiltInMic: true,
    Laser: "N/A",
    WDR: "140dB",
    Size: "Φ222x372mm (Φ8.74×14.65inch)",
    MicroSDCardStorage: "512 GB",
    AI: "Tripwire, Double Tripwire, Perimeter, Object Abandon, Object Lost, Loitering, Parking, Heatmap,People Counting, On Duty Detection, Safety Helmet Detection",
    IO: "Audio 1/1 Alarm 8/2",
    BuiltInSpeaker: false,
    Protection: "IP67",
    OnBoardStorage: "N/A",
    Material: "Metal+Plastic Housing",
    Price: 1060,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera5.png",
    Series: "Ultra Series - Panoramic PTZ Camera",
    model: "TC-H3169M Spec: 63X/ LW/P/A/AR",
    Features: [
      "Panaromic Camera",
      "·Four 1/1.8” CMOS",
      "·Up to 5520x2400@30fps",
      "·Horizontal: 180°, Verticle:85°",
      "·Min. illumination Color: 0.0004Lux@F1.0 ·Support region clipping",
      "·Support distortion correction",
      "-",
      "PTZ Camera",
      "·Up to 2560*1440@30fps",
      "·Suppport 3d position",
      "·Auto-Tracking Early Warning (AEW) ·Auto Wiper",
      "·IP66",
    ],
    Lens: "Panoramic: 2.8mm - PTZ: 5.7-359mm",
    Zoom: "Optical: 63x Digital: 16x",
    IRDistance: "300m",
    BuiltInMic: false,
    Laser: "500m",
    WDR: "Panoramic: Digital PTZ: True WDR ",
    Size: "Φ358x568 mm (Φ14.09×22.36 inch)",
    MicroSDCardStorage: "512 GB",
    AI: "Panoramic : Tripwire, Double Tripwire , Heatmap-PTZ : Tripwire, Double Tripwire, Perimeter, Object Abandon, Object Lost, Loitering, Parking, Heatmap, Crowd, People Counting, On Duty Detection, Auto tracking, Face Capture, Early Warning",
    IO: "Audio 1/1 Alarm 8/2",
    BuiltInSpeaker: false,
    Protection: "",
    OnBoardStorage: "N/A",
    Material: "Metal+Plastic Housing",
    Price: 0,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera5.png",
    Series: "Ultra Series - Panoramic PTZ Camera",
    model: "TC-H3169M Spec: 63X/ LW/P/A/AR",
    Features: [
      "Panaromic Camera",
      "·Four 1/1.8” CMOS",
      "·Up to 5520x2400@30fps",
      "·Horizontal: 180°, Verticle:85°",
      "·Min. illumination Color: 0.0004Lux@F1.0 ·Support region clipping",
      "·Support distortion correction",
      "-",
      "PTZ Camera",
      "·Up to 2560*1440@30fps",
      "·Suppport 3d position",
      "·Auto-Tracking Early Warning (AEW) ·Auto Wiper",
      "·IP66",
    ],
    Lens: "Panoramic: 2.8mm - PTZ: 5.7-359mm",
    Zoom: "Optical: 63x Digital: 16x",
    IRDistance: "300m",
    BuiltInMic: false,
    Laser: "500m",
    WDR: "Panoramic: Digital PTZ: True WDR ",
    Size: "Φ358x568 mm (Φ14.09×22.36 inch)",
    MicroSDCardStorage: "512 GB",
    AI: "Panoramic : Tripwire, Double Tripwire , Heatmap-PTZ : Tripwire, Double Tripwire, Perimeter, Object Abandon, Object Lost, Loitering, Parking, Heatmap, Crowd, People Counting, On Duty Detection, Auto tracking, Face Capture, Early Warning",
    IO: "Audio 1/1 Alarm 8/2",
    BuiltInSpeaker: false,
    Protection: "",
    OnBoardStorage: "N/A",
    Material: "Metal+Plastic Housing",
    Price: 0,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera5.png",
    Series: "Ultra Series - Panoramic PTZ Camera",
    model: "TC-H3169M Spec: 63X/ LW/P/A/AR",
    Features: [
      "Panaromic Camera",
      "·Four 1/1.8” CMOS",
      "·Up to 5520x2400@30fps",
      "·Horizontal: 180°, Verticle:85°",
      "·Min. illumination Color: 0.0004Lux@F1.0 ·Support region clipping",
      "·Support distortion correction",
      "-",
      "PTZ Camera",
      "·Up to 2560*1440@30fps",
      "·Suppport 3d position",
      "·Auto-Tracking Early Warning (AEW) ·Auto Wiper",
      "·IP66",
    ],
    Lens: "Panoramic: 2.8mm - PTZ: 5.7-359mm",
    Zoom: "Optical: 63x Digital: 16x",
    IRDistance: "300m",
    BuiltInMic: false,
    Laser: "500m",
    WDR: "Panoramic: Digital PTZ: True WDR ",
    Size: "Φ358x568 mm (Φ14.09×22.36 inch)",
    MicroSDCardStorage: "512 GB",
    AI: "Panoramic : Tripwire, Double Tripwire , Heatmap-PTZ : Tripwire, Double Tripwire, Perimeter, Object Abandon, Object Lost, Loitering, Parking, Heatmap, Crowd, People Counting, On Duty Detection, Auto tracking, Face Capture, Early Warning",
    IO: "Audio 1/1 Alarm 8/2",
    BuiltInSpeaker: false,
    Protection: "",
    OnBoardStorage: "N/A",
    Material: "Metal+Plastic Housing",
    Price: 0,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera5.png",
    Series: "Ultra Series - Panoramic PTZ Camera",
    model: "TC-H3169M Spec: 63X/ LW/P/A/AR",
    Features: [
      "Panaromic Camera",
      "·Four 1/1.8” CMOS",
      "·Up to 5520x2400@30fps",
      "·Horizontal: 180°, Verticle:85°",
      "·Min. illumination Color: 0.0004Lux@F1.0 ·Support region clipping",
      "·Support distortion correction",
      "-",
      "PTZ Camera",
      "·Up to 2560*1440@30fps",
      "·Suppport 3d position",
      "·Auto-Tracking Early Warning (AEW) ·Auto Wiper",
      "·IP66",
    ],
    Lens: "Panoramic: 2.8mm - PTZ: 5.7-359mm",
    Zoom: "Optical: 63x Digital: 16x",
    IRDistance: "300m",
    BuiltInMic: false,
    Laser: "500m",
    WDR: "Panoramic: Digital PTZ: True WDR ",
    Size: "Φ358x568 mm (Φ14.09×22.36 inch)",
    MicroSDCardStorage: "512 GB",
    AI: "Panoramic : Tripwire, Double Tripwire , Heatmap-PTZ : Tripwire, Double Tripwire, Perimeter, Object Abandon, Object Lost, Loitering, Parking, Heatmap, Crowd, People Counting, On Duty Detection, Auto tracking, Face Capture, Early Warning",
    IO: "Audio 1/1 Alarm 8/2",
    BuiltInSpeaker: false,
    Protection: "",
    OnBoardStorage: "N/A",
    Material: "Metal+Plastic Housing",
    Price: 0,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera5.png",
    Series: "Ultra Series - Panoramic PTZ Camera",
    model: "TC-H3169M Spec: 63X/ LW/P/A/AR",
    Features: [
      "Panaromic Camera",
      "·Four 1/1.8” CMOS",
      "·Up to 5520x2400@30fps",
      "·Horizontal: 180°, Verticle:85°",
      "·Min. illumination Color: 0.0004Lux@F1.0 ·Support region clipping",
      "·Support distortion correction",
      "-",
      "PTZ Camera",
      "·Up to 2560*1440@30fps",
      "·Suppport 3d position",
      "·Auto-Tracking Early Warning (AEW) ·Auto Wiper",
      "·IP66",
    ],
    Lens: "Panoramic: 2.8mm - PTZ: 5.7-359mm",
    Zoom: "Optical: 63x Digital: 16x",
    IRDistance: "300m",
    BuiltInMic: false,
    Laser: "500m",
    WDR: "Panoramic: Digital PTZ: True WDR ",
    Size: "Φ358x568 mm (Φ14.09×22.36 inch)",
    MicroSDCardStorage: "512 GB",
    AI: "Panoramic : Tripwire, Double Tripwire , Heatmap-PTZ : Tripwire, Double Tripwire, Perimeter, Object Abandon, Object Lost, Loitering, Parking, Heatmap, Crowd, People Counting, On Duty Detection, Auto tracking, Face Capture, Early Warning",
    IO: "Audio 1/1 Alarm 8/2",
    BuiltInSpeaker: false,
    Protection: "",
    OnBoardStorage: "N/A",
    Material: "Metal+Plastic Housing",
    Price: 0,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera5.png",
    Series: "Ultra Series - Panoramic PTZ Camera",
    model: "TC-H3169M Spec: 63X/ LW/P/A/AR",
    Features: [
      "Panaromic Camera",
      "·Four 1/1.8” CMOS",
      "·Up to 5520x2400@30fps",
      "·Horizontal: 180°, Verticle:85°",
      "·Min. illumination Color: 0.0004Lux@F1.0 ·Support region clipping",
      "·Support distortion correction",
      "-",
      "PTZ Camera",
      "·Up to 2560*1440@30fps",
      "·Suppport 3d position",
      "·Auto-Tracking Early Warning (AEW) ·Auto Wiper",
      "·IP66",
    ],
    Lens: "Panoramic: 2.8mm - PTZ: 5.7-359mm",
    Zoom: "Optical: 63x Digital: 16x",
    IRDistance: "300m",
    BuiltInMic: false,
    Laser: "500m",
    WDR: "Panoramic: Digital PTZ: True WDR ",
    Size: "Φ358x568 mm (Φ14.09×22.36 inch)",
    MicroSDCardStorage: "512 GB",
    AI: "Panoramic : Tripwire, Double Tripwire , Heatmap-PTZ : Tripwire, Double Tripwire, Perimeter, Object Abandon, Object Lost, Loitering, Parking, Heatmap, Crowd, People Counting, On Duty Detection, Auto tracking, Face Capture, Early Warning",
    IO: "Audio 1/1 Alarm 8/2",
    BuiltInSpeaker: false,
    Protection: "",
    OnBoardStorage: "N/A",
    Material: "Metal+Plastic Housing",
    Price: 0,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera5.png",
    series: "Ultra Series - Panoramic PTZ Camera",
    model: "TC-H3169M Spec: 63X/ LW/P/A/AR",
    Features: [
      "Panaromic Camera",
      "·Four 1/1.8” CMOS",
      "·Up to 5520x2400@30fps",
      "·Horizontal: 180°, Verticle:85°",
      "·Min. illumination Color: 0.0004Lux@F1.0 ·Support region clipping",
      "·Support distortion correction",
      "-",
      "PTZ Camera",
      "·Up to 2560*1440@30fps",
      "·Suppport 3d position",
      "·Auto-Tracking Early Warning (AEW) ·Auto Wiper",
      "·IP66",
    ],
    Lens: "Panoramic: 2.8mm - PTZ: 5.7-359mm",
    Zoom: "Optical: 63x Digital: 16x",
    IRDistance: "300m",
    BuiltInMic: false,
    Laser: "500m",
    WDR: "Panoramic: Digital PTZ: True WDR ",
    Size: "Φ358x568 mm (Φ14.09×22.36 inch)",
    MicroSDCardStorage: "512 GB",
    AI: "Panoramic : Tripwire, Double Tripwire , Heatmap-PTZ : Tripwire, Double Tripwire, Perimeter, Object Abandon, Object Lost, Loitering, Parking, Heatmap, Crowd, People Counting, On Duty Detection, Auto tracking, Face Capture, Early Warning",
    IO: "Audio 1/1 Alarm 8/2",
    BuiltInSpeaker: false,
    Protection: "",
    OnBoardStorage: "N/A",
    Material: "Metal+Plastic Housing",
    Price: 0,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
  {
    image: "/camera5.png",
    Series: "Ultra Series - Panoramic PTZ Camera",
    model: "TC-H3169M Spec: 63X/ LW/P/A/AR",
    Features: [
      "Panaromic Camera",
      "·Four 1/1.8” CMOS",
      "·Up to 5520x2400@30fps",
      "·Horizontal: 180°, Verticle:85°",
      "·Min. illumination Color: 0.0004Lux@F1.0 ·Support region clipping",
      "·Support distortion correction",
      "-",
      "PTZ Camera",
      "·Up to 2560*1440@30fps",
      "·Suppport 3d position",
      "·Auto-Tracking Early Warning (AEW) ·Auto Wiper",
      "·IP66",
    ],
    Lens: "Panoramic: 2.8mm - PTZ: 5.7-359mm",
    Zoom: "Optical: 63x Digital: 16x",
    IRDistance: "300m",
    BuiltInMic: false,
    Laser: "500m",
    WDR: "Panoramic: Digital PTZ: True WDR ",
    Size: "Φ358x568 mm (Φ14.09×22.36 inch)",
    MicroSDCardStorage: "512 GB",
    AI: "Panoramic : Tripwire, Double Tripwire , Heatmap-PTZ : Tripwire, Double Tripwire, Perimeter, Object Abandon, Object Lost, Loitering, Parking, Heatmap, Crowd, People Counting, On Duty Detection, Auto tracking, Face Capture, Early Warning",
    IO: "Audio 1/1 Alarm 8/2",
    BuiltInSpeaker: false,
    Protection: "",
    OnBoardStorage: "N/A",
    Material: "Metal+Plastic Housing",
    Price: 0,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda voluptatem ducimus soluta tempora, et quas sed ab quae dignissimos dolorem.",
  },
];
